export const MODAL_VISIBLE = 'MODAL_VISIBLE';

export const TASK_ADD_TASK = 'TASK_ADD_TASK';
export const TASK_EDIT_TASK = 'TASK_EDIT_TASK';
export const TASK_REMOVE_TASK = 'TASK_REMOVE_TASK';
export const TASK_BULK_REMOVE_TASK = 'TASK_BULK_REMOVE_TASK';
export const TASK_TOGGLE_BOOKMARK = 'TASK_TOGGLE_BOOKMARK';
export const TASK_TOGGLE_CHECK = 'TASK_TOGGLE_CHECK';